def get_extra_patterns(category_word, distractors, punct, category, words):

    return [
        rf"из выбранных слов, {category_word} является {category}.",
        rf"из выбранных слов, {category_word} является именем родства.",
        rf"из выбранных слов, только {category_word} является {category}.",
        rf"из выбранных слов, {category_word} входит в категорию {category}.",
        rf"из выбранных слов, {category_word} связан с категорией {category}.",
        rf"из выбранных слов, {category_word} попадает в категорию {category}.",
        rf"из выбранных слов, {category_word} связана с категорией {category}.",
        rf"из выбранных слов, {category} относится к категории {category_word}.",
        rf"из выбранных слов, {category_word} относится к категории {category}.",
        rf"из выбранных слов, {category_word} представляет категорию {category}.",
        rf"из выбранных слов, {category_word} соответствует категории {category}.",
        rf"из выбранных слов, {category_word} принадлежит к категории {category}.",
        rf"из выбранных слов, {category_word} и {category} входят в категорию {category}.",
        rf"из выбранных слов, {category_word} согласуется с категорией {category}.",
        rf"из выбранных слов, {category_word} и {category} относятся к категории {category}.",
        rf"из выбранных слов, только {category_word} входит в категорию {category}.",
        rf"из выбранных слов, {category_word} является частью категории {category}.",
        rf"из выбранных слов, только {category_word} связан с категорией {category}.",
        rf"из выбранных слов, {category_word} ассоциируется с категорией {category}.",
        rf"из выбранных слов, {category_word} и {category} относятся к категории {category}.",
        rf"из выбранных слов, только {category_word} попадает в категорию {category}.",
        rf"из выбранных слов, только {category_word} связано с категорией {category}.",
        rf"из выбранных слов, только {category_word} связана с категорией {category}.",
        rf"из выбранных слов, {category_word} является объектом категории {category}.",
        rf"из выбранных слов, {category_word} и {category} соответствуют категории {category}.",
        rf"из выбранных слов, {category_word} и {category} представляют категорию {category}.",
        rf"из выбранных слов, только {category_word} относится к категории {category}.",
        rf"из выбранных слов, {category_word} и {category} соответствуют категории {category}.",
        rf"из выбранных слов, только {category_word} соответствует категории {category}.",
        rf"из выбранных слов, только {category_word} принадлежит к категории {category}.",
        rf"из выбранных слов, только {category_word} согласуется с категорией {category}.",
        rf"из выбранных слов, {category_word} является связанным с категорией {category}.",
        rf"из выбранных слов, только {category_word} является частью категории {category}.",
        rf"из выбранных слов, {category_word} и {category} связаны с категорией {category}.",
        rf"из выбранных слов, только {category_word} ассоциируется с категорией {category}.",
        rf"из выбранных слов, только {category_word} имеет отношение к категории {category}.",
        rf"из выбранных слов, {category_word} является согласованным с категорией {category}.",
        rf"из выбранных слов, {category_word} и {category} могут быть объединены в категорию {category}.",
        rf"из выбранных слов, только {category_word} согласуется с категорией {category}.",
        rf"из выбранных слов, {category_word} является {category}, так как {category_word} - это {category}.",
        rf"из выбранных слов, {category_word} и {category} могут быть объединены в категорию {category}.",
        rf"из выбранных слов, {category_word} является тем, который связан с категорией {category}.",
        rf"из выбранных слов, только {category_word} является согласованным с категорией {category}.",
        rf"из выбранных слов, {category_word} является {category} и принадлежит к категории {category}.",
        rf"из выбранных слов, {category_word} является тем, который можно отнести к категории {category}.",
        rf"из выбранных слов, {category_word} является объектом, который относится к категории {category}.",
        rf"из выбранных слов, {category_word} является {category}, так как оно означает {category_word}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому оно входит в категорию {category}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому оно представляет категорию {category}.",
        rf"из выбранных слов, {category_word} является объектом, который может быть отнесен к категории {category}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому оно соответствует категории {category}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому вы можете выбрать ее из категории {category}.",
        rf"из выбранных слов, {category_word} ассоциируется с категорией {category}.",
        rf"из выбранных слов, только {category_word} имеет отношение к категории {category}.",
        rf"из выбранных слов, {category_word} является {category}.",
        rf"из выбранных слов, {category_word} является частью категории {category}, так как {category_word} - это {category}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому вы можете выбрать его из категории {category}.",
        rf"из выбранных слов, {category_word} является {category}, так как это название принадлежит к категории {category}.",
        rf"из выбранных слов, только {category_word} имеет отношение к категории {category}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому оно может быть объединено в категорию {category}.",
        rf"из выбранных слов, {category_word} связано с категорией {category}.",
        rf"из выбранных слов, {category_word} связана с категорией {category}.",
        rf"из выбранных слов, {category_word} является частью категории {category}.",
        rf"из выбранных слов, {category_word} является {category}, поэтому вы можете выбрать ее из списка.\nтаким образом, выберите {category_word}.",
        rf"из предложенных слов, {category_word} является {category}.",
        rf"из предложенных слов, {category_word} является {category}.",
        rf"из предложенных слов, {category_word} является {category}.",
        rf"из предложенных слов, только {category_word} является {category}.",
        rf"из предложенных слов, {category_word} входит в категорию {category}.",
        rf"из предложенных слов, {category_word} и {category} входят в категорию {category}.",
        rf"из предложенных слов, {category_word} соответствует категории {category}.",
        rf"из предложенных слов, только {category_word} являются частью категории {category}.",
        rf"из предложенных слов, {category_word} является частью категории {category}.",
        rf"из предложенных слов, {category_word} и {category} относятся к категории {category}.",
        rf"из предложенных слов, {category_word} может быть отнесена к категории {category}.",
        rf"из предложенных слов, только {category_word} входит в категорию {category}.",
        rf"из предложенных слов, только {category_word} связан с категорией {category}.",
        rf"из предложенных слов, {category_word} и {category} представляют категорию {category}.",
        rf"из предложенных слов, {category_word} ассоциируется с категорией {category}.",
        rf"из предложенных слов, только {category_word} попадает в категорию {category}.",
        rf"из предложенных слов, только {category_word} связана с категорией {category}.",
        rf"из предложенных слов, только {category_word} связано с категорией {category}.",
        rf"из предложенных слов, только {category_word} относится к категории {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, {category_word} и {category} являются частью категории {category}.",
        rf"из предложенных слов, только {category_word} представляет категорию {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, только {category_word} соответствует категории {category}.",
        rf"из предложенных слов, только {category_word} принадлежит к категории {category}.",
        rf"из предложенных слов, только {category_word} согласуется с категорией {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесена к категории {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесена к категории {category}.",
        rf"из предложенных слов, только {category_word} является частью категории {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, только {category_word} ассоциируется с категорией {category}.",
        rf"из предложенных слов, только {category_word} может быть отнесено к категории {category}.",
        rf"из предложенных слов, только {category_word} имеет отношение к категории {category}.",
        rf"из предложенных слов, {category_word} и {category} могут быть объединены в категорию {category}.",
        rf"из предложенных слов, только {category_word} может быть связан с категорией {category}.",
        rf"из предложенных слов, только {category_word} может быть связана с категорией {category}.",
        rf"из предложенных слов, только {category_word} может быть связано с категорией {category}.",
        rf"из предложенных слов, только {category_word} соответствует категории {category}, так как {distractors} не являются {category}.",
        rf"из предложенных слов, только {category_word} согласуется с категорией {category}, так как {distractors} не являются {category}.",
        rf"да{punct} все слова в списке {words} не являются {category}.",
        rf"да{punct} все слова из списка {words} не являются {category}.",
        rf"да{punct} все слова из списка {words} не относятся к категории {category}.",
        rf"да{punct} все слова из списка {words} не являются {category} и соответственно не согласованы с категорией {category}.",
        rf"да{punct} из списка выбрано слово {category_word}.",
        rf"да{punct} из списка слов {words} есть {category}.",
        rf"да{punct} из списка слов {words} есть {category} - {category_word}.",
        rf"да{punct} из списка слов {category} входит слово {category_word}.",
        rf"да{punct} из списка слов {words} существует слово {category_word}.",
        rf"да{punct} из списка слов {words} есть один {category} - {category_word}.",
        rf"да{punct} из списка слов {words} существует {category} - {category_word}.",
        rf"да{punct} из списка предлагаемых слов можно выбрать {category_word}.",
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить {category} {category_word}.",
        rf"да{punct} из списка слов {words} есть один {category} {category_word}.",
        rf"да{punct} из списка слов {words} существует {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить {category} - {category_word}.",
        rf"да{punct} из списка слов {category} связано слово {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить {category} - {category_word}.",
        rf"да{punct} из списка слов {words} существует {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно выбрать {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно выбрать категорию {category}.",
        rf"да{punct} из списка слов {words} принадлежит к категории {category}.",
        rf"да{punct} из списка слов {words} можно выбрать {category} - {category_word}.",
        rf"да{punct} из списка слов {words} существует {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно отнести к категории {category}.",
        rf"да{punct} из списка слов {words} можно выбрать {category} - {category_word}.",
        rf"да{punct} из списка слов {category} входит слово {category_word}.",
        rf"да{punct} из списка слов {words} можно выбрать {category} - {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить {category} - {category_word}.",
        rf"да{punct} из списка слов {words} ассоциируется с категорией {category}.",
        rf"да{punct} из списка слов {category} входит слово {category_word}.",
        rf"да{punct} из списка выделенных слов, {category_word} является {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, есть слово {category}.",
        rf"да{punct} из списка предлагаемых слов, {category_word} является {category}.",
        rf"да{punct} из списка слов {words} можно согласовать с категорией {category}.",
        rf"да{punct} из списка предложенных слов следует выделить {category_word} как {category}.",
        rf"да{punct} из списка слов, вы можете отнести {category_word} к категории {category}.",
        rf"да{punct} из списка слов {words} только {category_word} является {category}.",
        rf"да{punct} из списка слов {words} можно найти {category}.\n{category}: {category_word}"
        rf"да{punct} из списка слов, вы можете соотносить {category_word} с категорией {category}.",
        rf"да{punct} из списка слов {words} только {category_word} относятся к категории {category}.",
        rf"да{punct} из списка слов, вы можете ассоциировать {category_word} с категорией {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} является {category}.",
        rf"да{punct} из списка слов, указанных в вопросе, {category_word} является {category}.",
        rf"да{punct} из списка выделенных слов, {category} соответствует слову {category_word}.",
        rf"да{punct} из списка выделенных слов, {category_word} связан с категорией {category}.",
        rf"да{punct} из списка слов, выделенных в запросе, {category_word} является {category}.",
        rf"да{punct} из списка выделенных слов, {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} является {category}.",
        rf"да{punct} из списка слов {words} связано с категорией {category} слово {category_word}.",
        rf"да{punct} из списка предложенных слов, {category_word} относится к категории {category}.",
        rf"да{punct} из списка предлагаемых слов, {category_word} является {category}.",
        rf"да{punct} из списка слов {words} отношение к категории {category} есть только для {category_word}.",
        rf"да{punct} из списка слов {words} только {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}, потому что это {category}.",
        rf"да{punct} из списка слов {words} есть слово {category_word}, которое является {category}.",
        rf"да{punct} из списка выделенных слов, {category_word} является частью категории {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} имеет связь с категорией {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} является {category}.",
        rf"да{punct} из списка слов {words} только {category_word} может быть отнесена к категории {category}.",
        rf"да{punct} из списка слов {words} только {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} из списка выделенных слов, слово {category_word} будет согласоваться с категорией {category}.",
        rf"да{punct} из списка слов, выделенных в вопросе, только {category_word} относятся к категории {category}.",
        rf"да{punct} из списка слов {words} только {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} связано с категорией {category}.",
        rf"да{punct} из списка предлагаемых слов, {category} может быть связано с словом {category_word}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\n{category_word} - это {category}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\n* {category_word} - это {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} относится к категории {category}.",
        rf"да{punct} из списка выбрано слово {category_word}, которое соотносится с категорией {category}.",
        rf"да{punct} из списка слов {words} есть слово, связанное с категорией {category}: {category_word}.",
        rf"да{punct} из списка слов {words} только слово {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} из списка выделены следующие слова, которые относятся к категории {category}:\n\n* {category_word},"
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} связан с категорией {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} соотносится с категорией {category}.",
        rf"да{punct} из списка слов есть связь с категорией {category}. слово {category_word} относится к {category}.",
        rf"да{punct} из списка слов, выделенных в вопросе, отношение к категории {category} имеет слово {category_word}.",
        rf"да{punct} из списка выделенных слов {words} только {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только слово {category_word} является {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} из списка слов {words} только слово {category_word} имеет отношение к категории {category}.",
        rf"да{punct} из списка слов, выделенных в вопросе, только слово {category_word} относятся к категории {category}.",
        rf"да{punct} из списка слов, выделенных в запросе, отношение к категории {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}, которое является {category}.",
        rf"да{punct} из списка слов, выделенных в запросе, связано с категорией {category} слово {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить слово {category_word}, которое является {category}.",
        rf"да{punct} из списка слов, выделенных в запросе, отношение к категории {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} может быть отнесена к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} может быть отнесен к категории {category}.",
        rf"да{punct} из списка слов, выделенных в запросе, есть слово {category_word}, которое является {category}.",
        rf"да{punct} из списка слов, выделенных в вопросе, только {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, следует выделить слово {category_word} в категории {category}.",
        rf"да{punct} из списка перечисленных слов следует выделить {category_word}, так как это действительно {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} ассоциируется с категорией {category}.",
        rf"да{punct} из списка слов есть связь с категорией {category}:\n\n* {category_word} - это {category}.\nответ: да.",
        rf"да{punct} из списка слов, которые вы предоставили, связано с категорией {category} слово {category_word}.",
        rf"да{punct} из списка слов, выделенных в запросе, есть связь между словом {category_word} и категорией {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только {category_word} связано с категорией {category}.",
        rf"да{punct} из списка слов есть связь с категорией {category}. слово {category_word} является {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, есть слово {category_word}, которое является {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, {category_word} (отец) относится к категории {category}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\n{category_word} - это {category}.\n\nответ: да.",
        rf"да{punct} из списка слов есть слово, связанное с категорией {category}:\n\n* {category_word} - это {category}.",
        rf"да{punct} из списка слов {words} есть одно слово, которое относится к категории {category}:\n\n{category_word}.",
        rf"да{punct} из списка слов {words} есть слово, которое имеет отношение к категории {category}: {category_word}.",
        rf"да{punct} из списка слов, указанных в вопросе, только {category_word} имеет отношение к категории {category}.",
        rf"да{punct} из списка слов есть связь с категорией {category}. слово {category_word} относится к этой категории.",
        rf"да{punct} из списка слов, выделенных в вопросе, только слово {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, выделенных в вопросе, есть слово {category_word}, которое относятся к категории {category}.",
        rf"да{punct} из списка слов {words} ассоциируется с категорией {category} слов {category_word} и {category_word}.",
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}, которое относится к категории {category}.",
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}, которое является механизмом или прибором.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nслово {category_word} является {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только {category_word} ассоциируется с категорией {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только слово {category_word} относится к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только слово {category_word} может быть отнесено к категории {category}.",
        rf'да{punct} из списка слов {words} есть связь с категорией {category}. {category_word} является {category}. ответ "да".',
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}, потому что {category_word} является типом {category}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}. слово {category_word} является {category}.",
        rf"да{punct} из списка слов, выделенных в вопросе, только слово {category_word} имеет отношение к категории {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только слово {category_word} ассоциируется с категорией {category}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов {words} есть связность с категорией {category}. слово {category_word} входит в эту категорию.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов, выделенных в вопросе, только слово {category} может быть согласовано с категорией {category}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов, которые вы предоставили, только слово {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} из списка слов {words} есть связность с категорией {category}. слово {category_word} является {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, есть слово {category_word}, которое связано с категорией {category}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов {words} можно выделить одно слово, которое относится к категории {category}:\n\n* {category_word},"
        rf"да{punct} из списка слов {words} есть связь с категорией {category}.\n\nсвязь с категорией {category} имеет слово {category_word}.",
        rf"да{punct} из списка слов {words} есть слово, которое относится к категории {category}:\n\n{category_word} - это {category}.",
        rf"да{punct} из списка слов, которые вы предоставили, только {category_word} является {category}.\nслова {distractors} не являются {category}.",
        rf'да{punct} из списка слов есть связь с категорией {category}:\n\n* {category_word} - это {category}\n\nтаким образом, ответ на ваш вопрос - "да".',
        rf"да{punct} из списка слов {words} есть слово, которое связано с категорией {category}:\n\n{category_word} - это {category}.",
        rf"да{punct} из списка выделенных слов следующие являются {category}:\n\n* {category_word} ({category})\n\nостальные слова {distractors} не являются {category}.",
        rf"да{punct} из списка выделенных слов следующие согласуются категорией {category}:\n\n* {category_word}\n\nостальные слова {distractors} не являются {category}.",
        rf"да{punct} из списка выделены следующие {category}:\n\n* {category_word} ({category})\n\nтаким образом, из списка {words} представлены следующие {category}: {category_word}.",
        rf"да{punct} из списка слов {words} есть связность с категорией {category}.\n\n{category_word} является {category}.",
        rf"да{punct} из списка слов {words} можно выбрать слово {category_word}, которое относится к категории {category}.",
        rf'да{punct} из списка выделенных слов следующие соответствуют категории {category}:\n\n* {category_word} - это {category}\n\nтаким образом, ответ на ваш вопрос - "да".',
        rf"да{punct} из списка слов, вы можете найти {category} в следующих словах:\n\n* {distractors} - нет\n* {distractors} - нет\n* {category_word} - да\n* {distractors} - нет\n* {distractors} - нет",
        rf"да{punct} из списка выделенных слов следующие попадают в категорию {category}:\n\n* {distractors} - нет\n* {distractors} - нет\n* {distractors} - нет\n* {distractors} - нет\n* {category_word} - да",
        rf"да{punct} из списка слов {words} есть связность с категорией {category}.\n\n{category_word} является {category}.",
        rf"да{punct} из списка слов {words} есть связность с категорией {category}.\n\nслово {category_word} является {category}.",
        rf'да{punct} из списка слов есть связь с категорией {category}:\n\n* {category} - это слово входит в категорию {category}\n\nтаким образом, ответ на ваш вопрос - "да".',
        rf"да{punct} из списка слов {words} есть слово, которое имеет отношение к категории {category}:\n\n{category_word} - это {category}, которое означает {category_word}.",
        rf"да{punct} из списка выделенных слов следующие являются частью категории {category}:\n\n* {category_word}\n\nостальные слова {distractors} не являются частью этой категории.",
        rf"да{punct} некоторые слова из списка имеют отношение к категории {category}:\n\n* {category_word} - да\n* {distractors} - нет\n* {distractors} - нет\n* {distractors} - нет\n* {distractors} - нет",
        rf"да{punct} слово {category_word} входит в список.",
        rf"да{punct} слово {category_word} является {category}.",
        rf"да{punct} слово {category_word} относится к этой категории.",
        rf"да{punct} слово {category_word} соответствует этой категории.",
        rf"да{punct} слово {category_word} находится в категории {category}.",
        rf"да{punct} слово {category_word} находится в списке {category}.",
        rf"да{punct} слово {category_word} находится в категории {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.",
        rf"да{punct} слово {category_word} является категорией {category}.",
        rf"да{punct} слово {category_word} связано с категорией {category}.",
        rf"да{punct} слово {category_word} включено в категорию {category}.",
        rf"да{punct} слово {category_word} находится в категории {category}.",
        rf"да{punct} слово {category_word} попадает в категорию {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.",
        rf"да{punct} слово {category_word} относится к категории {category}.",
        rf"да{punct} слово {category_word} относятся к категории {category}.",
        rf"да{punct} слово {category_word} находится в категории {category}.",
        rf"да{punct} слово {category_word} принадлежит категории {category}.",
        rf"да{punct} слово {category_word} находится в категории {category}.",
        rf"да{punct} слово {category_word} будет частью категории {category}.",
        rf"да{punct} слово {category_word} включается в категорию {category}.",
        rf"да{punct} слово {category_word} соответствует категории {category}.",
        rf"да{punct} слово {category_word} соотносимо с категорией {category}.",
        rf"да{punct} слово {category_word} связано с категорией {category}.",
        rf"да{punct} слово {category_word} принадлежит к категории {category}.",
        rf"да{punct} слово {category_word} согласовано с категорией {category}.",
        rf"да{punct} слово {category_word} соотносится с категорией {category}.",
        rf"да{punct} слово {category_word} согласуется с категорией {category}.",
        rf"да{punct} слово {category_word} имеет связь с категорией {category}.",
        rf"да{punct} слово {category_word} относится к категории {category}.",
        rf"да{punct} слово {category_word} было включено в категорию {category}.",
        rf"да{punct} слово {category_word} является частью категории {category}.",
        rf"да{punct} слово {category_word} связано с категорией {category_word}.",
        rf"да{punct} слово {category_word} можно отнести к категории {category}.",
        rf"да{punct} слово {category_word} связано с {category}.",
        rf"да{punct} слово {category_word} ассоциируется с категорией {category}.",
        rf"да{punct} слово {category_word} относится к категории {category_word}.",
        rf"да{punct} слово {category_word} будет включено в категорию {category}.",
        rf"да{punct} слово {category_word} имеет отношение к категории {category}.",
        rf"да{punct} слово {category_word} связано с категорией {category}.",
        rf"да{punct} слово {category_word} соответствует категории {category_word}.",
        rf"да{punct} слово {category_word} будет включаться в категорию {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.\n\nответ: да,"
        rf"да{punct} слово {category_word} согласуется с категорией {category}.",
        rf"да{punct} слово {category_word} является частью категории {category}.",
        rf"да{punct} слово {category_word} имеет связь с категорией {category}.",
        rf"да{punct} слово {category_word} из списка включено в категорию {category}.",
        rf"да{punct} слово {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} слово {category_word} является частью категории {category}.",
        rf"да{punct} слово {category_word} из списка соответствует категории {category}.",
        rf"да{punct} слово {category_word} связано с категорией {category}.",
        rf"да{punct} слово {category_word} относится к категории {category}.",
        rf"да{punct} слово {category_word} может быть связано с категорией {category}.",
        rf"да{punct} слово {category_word} может быть ассоциировано с категорией {category}.",
        rf"да{punct} слово {category_word} из списка {words} является категорией {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.",
        rf"да{punct} слово {category_word} имеет связь с категорией {category}.",
        rf"да{punct} слово {category_word} является частью категории {category}.",
        rf"да{punct} слово {category_word} можно отнести к категории {category}.",
        rf"да{punct} слово {category_word} связано с {category}.",
        rf"да{punct} слово {category_word} является {category} и соответствует категории {category}.",
        rf"да{punct} слово {category_word} относятся к категории {category}.",
        rf"да{punct} слово {category_word} является {category}, поэтому ответ на ваш вопрос - {category_word}.",
        rf"да{punct} слово {category_word} имеет связь с категорией {category}, так как {category_word} - это {category}.",
        rf"да{punct} слово {category_word} в списке {category}.\n\nнет, слова {distractors} не относятся к категории {category}.",
        rf"да{punct} слово {category_word} имеет отношение к категории {category}, так как {category_word} - это {category}.\nответ: да.",
        rf"да{punct} слово {category_word} находится в категории {category}.\n\nнет, слова {distractors} не являются {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.\n\nслова {distractors} не входят в категорию {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.\n\nнет, слова {distractors} не входят в категорию {category}.",
        rf"да{punct} слово {category_word} является словом, связанным с {category}. поэтому ответ на ваш вопрос - {category_word}.",
        rf"да{punct} слово {category_word} можно объединить в категорию {category}, так как оно является типом {category}.",
        rf"да{punct} слово {category_word} имеет отношение к категории {category}, так как {category_word} - это {category}.\nответ: да.",
        rf"да{punct} слово {category_word} попадает в категорию {category}.\n\nнет, слова {distractors} не попадают в категорию {category}.",
        rf"да{punct} слово {category_word} относится к категории {category}.\n\nнет, слова {distractors} не относятся к категории {category}.",
        rf"да{punct} слово {category_word} находится в категории {category}.\n\nнет, слова {distractors} не относятся к категории {category}.",
        rf"да{punct} слово {category_word} соответствует категории {category}.\n\nнет, слова {distractors} не соответствуют категории {category}.",
        rf"да{punct} слово {category_word} принадлежит к категории {category}.\n\nнет, слова {distractors} не принадлежат к категории {category}.",
        rf"да{punct} слово {category_word} принадлежит к категории {category}.",
        rf"да{punct} слово {category_word} является частью категории {category}.\nнет. слова {distractors} не являются частью категории {category}.",
        rf"да{punct} слово {category_word} является частью категории {category}.",
        rf"нет{punct} эти слова не были объединены в категорию {category}. они являются разными словами и не связаны между собой в какой-либо категории.",
        rf"нет{punct} эти слова не относятся к категории {category}.",
        rf"нет{punct} слова из списка {words} не являются {category}.",
        rf"нет{punct} слова из списка {distractors} не являются {category}.",
        rf"нет{punct} слова из списка {words} не являются типами {category}.",
        rf"нет{punct} слова из списка {words} не относятся к категории {category}.",
        rf"нет{punct} слова из списка {words} не являются частью категории {category}.",
        rf"нет{punct} слова из списка {words} не были включены в категорию {category}.",
        rf"нет{punct} слова из списка {words} не являются частьями категории {category}.",
        rf"нет{punct} слова из списка {words} не являются словами из категории {category}.",
        rf"нет{punct} слова из списка {words} не являются терминами, связанными с {category}.",
        rf"нет{punct} слова из списка {words} не являются связанными с категорией {category}.",
        rf"нет{punct} слова из списка {distractors} не являются словами из категории {category}.",
        rf"нет{punct} слова из списка {words} не являются словами, связанными с категорией {category}.",
        rf"нет{punct} слова из списка {words} не являются словами, относящимися к категории {category}.",
        rf"нет{punct} слова из списка {words} не являются {category} и не относятся к категории {category}.",
        rf"нет{punct} слова из списка {distractors} не являются словами, связанными с категорией {category}.",
        rf"нет{punct} слова из списка {words} не являются {category} и не учитываются в категории {category}.",
        rf"нет{punct} слова из списка {words} не относятся к категории {category}. они являются разными словами, которые обозначают разные вещи.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. каждое слово имеет свой отдельный смысл и использование в языке.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. эти слова принадлежат к разным категориям и имеют разные значения.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. каждое из этих слов имеет свой отдельный смысл и использование в языке.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. каждое из этих слов относится к разным областям и не связано с {category}.",
        rf"нет{punct} слова из списка {distractors} не являются {category}.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. каждое слово имеет свой отдельный смысл и принадлежит к разным категориям.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. каждое слово имеет свой отдельный и уникальный смысл и использование в языке.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. эти слова не имеют никакого отношения к {category} и не могут быть отнесены к этой категории.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. эти слова принадлежат к разным категориям лексики и не связаны между собой в качестве имён родства.",
        rf"нет{punct} слова из списка {words} не были объединены в категорию {category}. каждое слово имеет свой отдельный смысл и значение, и они не связаны между собой в какой-либо категории.",
        rf"нет{punct} все слова в списке не являются {category}:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не {category}' for distractor in distractors])}",
        rf"нет{punct} все слова в списке не входят в категорию {category}:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не {category}' for distractor in distractors])}",
        rf"нет{punct} все слова из списка не входят в категорию {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - это не {category}' for distractor in distractors])}",
        rf"нет{punct} все слова из списка не относятся к категории {category}:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не {category}' for distractor in distractors])}",
        rf"нет{punct} слова {words} не являются {category}.",
        rf"нет{punct} слова {words} не входят в категорию {category}.",
        rf"нет{punct} слова {words} не относятся к категории {category}.",
        rf"нет{punct} слова {words} не являются частью категории {category}.",
        rf"нет{punct} слова {words} не были включены в категорию {category}.",
        rf"нет{punct} слова {words} не являются частьями категории {category}.",
        rf"нет{punct} слова {words} не являются словами, связанными с категорией {category}.",
        rf"нет{punct}\nслова {words} не являются словами, связанными с категорией {category}.",
        rf"нет{punct} слова {words} не были включены в категорию {category} в данном словаре.",
        rf"нет{punct} слова {words} не являются {category} и не входят в категорию {category}.",
        rf"нет{punct} слова {words} не являются {category} и не включены в категорию {category}.",
        rf"нет{punct} слова {words} не являются {category} и не объединены в категорию {category}.",
        rf"нет{punct}\nслова {words} не являются {category}. они являются именами, словами, терминами или понятиями, которые не связаны с категорией {category}.",
        rf"нет{punct} слова {words} не являются {category}. они являются отдельными словами или терминами, которые могут использоваться в различных контекстах, но не являются {category} в целом.",
        rf"нет{punct} категория {category} не содержит слова из списка {words}.",
        rf"нет{punct} категория {category} не принимает слова из списка {words}.",
        rf"нет{punct} категория {category} не связана с любым из слов в списке: {words}.",
        rf"нет{punct} категория {category} не распространяется на слова {words}, так как эти слова не являются {category}.",
        rf"нет{punct} категория {category} не охватывает слова из списка {words}, так как эти слова не являются {category}.",
        rf"нет{punct} категория {category} не принимает слова из списка {words}, так как эти слова не относятся к {category}.",
        rf"нет{punct} категория {category} не включает слова из списка {words}, так как эти слова не являются типами {category}.",
        rf"нет{punct} категория {category} не учитывает слова из списка {words}, так как эти слова не являются типами {category}.",
        rf"нет{punct} категория {category} не принимает слова из списка {words}, так как эти слова не являются типами {category}.",
        rf"нет{punct} категория {category} не распространяется на слова {words}, так как эти слова не относятся к этой категории.",
        rf"нет{punct} категория {category} не распространяется на слова из списка {words}, так как эти слова не являются {category}.",
        rf"нет{punct} категория {category} не распространяется на слова из списка {words}, так как эти слова не относятся к {category}.",
        rf"нет{punct} категория {category} не распространяется на слова из списка {words}, так как эти слова не относятся к этой категории.",
        rf"нет{punct} категория {category} не распространяется на слова из списка {words}, так как эти слова не относятся к {category}.",
        rf"нет{punct} категория {category} не распространяется на слова из списка {words}, так как эти слова не имеют отношения к {category}.",
        rf"нет{punct} категория {category} не связана с любыми словами из списка {words}. эти слова принадлежат к разным категориям и не связаны с {category}.",
        rf"нет{punct} категория {category} не принимает слова из списка {words}. эти слова не являются типами {category} и не могут быть отнесены к этой категории.",
        rf"нет{punct} категория {category} не связана с любыми словами из списка {words}. эти слова принадлежат к разным категориям и не имеют отношения к {category}.",
        rf"нет{punct} категория {category} не распространяется на слова из списка:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не {category}' for distractor in distractors])}"
        rf"нет{punct} категория {category} не принимает слова из списка {distractors} в качестве своих элементов. эти слова не относятся к {category} и не могут быть использованы в качестве примеров для этой категории.",
        rf"из списка слов, только {category_word} принадлежит к категории {category}.",
        rf"из списка слов, только {category_word} является {category}. ответ: {category_word}.",
        rf"из списка слов, только {category_word} относится к категории {category}.\n\nответ: да.",
        rf"из списка слов, только {category_word} принадлежит к категории {category}.\n\nответ: да.",
        rf"из списка слов, только {category_word} имеет отношение к категории {category}. ответ: {category_word}.",
        rf"из списка слов, вы можете найти слово {category_word}, которое имеет отношение к категории {category}.",
        rf"да{punct} слова {category} и {category_word} связаны с категорией {category}.",
        rf"нет{punct} {category} не является частью списка {words}.",
        rf"нет{punct} {category} не является частью словаря {words}.",
        rf"нет{punct} {category} не является словом из списка {words}.",
        rf"нет{punct} {category} не является частью категории {words}.",
        rf"нет{punct} {category} не является частью списка слов {words}.",
        rf"нет{punct} {category} не соответствует слову {category_word}.",
        rf"нет{punct} {category} не является каким-либо из слов из списка.",
        rf"нет{punct} {category} не связано с любым словом из списка {words}.",
        rf"нет{punct} {category} не связано с любым из слов из списка {words}.",
        rf"нет{punct} {category} не является каким-либо из слов из списка {words}.",
        rf"нет{punct} {category} не ассоциируется с любым из слов из списка: {words}.",
        rf"нет{punct} {category} не соответствует какому-либо из выбранных слов из списка.",
        rf"нет{punct} {category} не является частью категории {words}.\n\n{category} - это отдельная категория, которая не связана с другими словами в списке.",
        rf"нет{punct} {category} не связано с любым из слов из списка:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не связано' for distractor in distractors])}"
        rf"да{punct} из этого списка только {category_word} связана с категорией {category}.",
        rf"да{punct} из этого списка только слово {category_word} связано с категорией {category}.",
        rf"да{punct} из этого списка только слово {category_word} относится к категории {category}.",
        rf"да{punct} из этого списка только слово {category_word} ассоциируется с категорией {category}.",
        rf"да{punct} из этого списка только слово {category_word} имеет отношение к категории {category}.",
        rf"да{punct} из этого списка только {category_word} является термином, который связан с категорией {category}.",
        rf"да{punct} из этого списка только {category_word} является {category}.\n{distractors} не являются {category}.",
        rf"да{punct} категория {category} включает слово {category_word}.",
        rf"да{punct} категория {category} может включать слово {category_word}.",
        rf"да{punct} категория {category} включает в себя слово {category_word}.",
        rf"да{punct} категория {category} соответствует слову {category_word}.",
        rf"да{punct} категория {category} может быть связана с словом {category}.",
        rf"да{punct} категория {category} может содержать слова из списка {words}.",
        rf"да{punct} категория {category} может принимать слова из списка {words}.",
        rf"да{punct} категория {category} может быть связана с словом {category_word}.",
        rf"да{punct} категория {category} соответствует слову {category_word} из списка.",
        rf"да{punct} с категорией {category} связано слово {category_word}.",
        rf"да{punct} с категорией {category} ассоциируется слово {category_word}.",
        rf"нет{punct} из списка предложенных слов нет слова {category}.",
        rf"нет{punct} из списка слов нет ничего связано с категорией {category}.",
        rf"нет{punct} из списка слов, которые вы предоставили, нет слова {category}.",
        rf"нет{punct} из списка слов {words} нет слова, которое является категорией {category}.",
        rf"нет{punct} из списка слов {words} нет слов, которые представляют категорию {category}.",
        rf"нет{punct} из списка предложенных слов нет слова, которое представляет категорию {category}.",
        rf"нет{punct} из списка слов, указанных в вопросе, нет слов, которые входят в категорию {category}.",
        rf"нет{punct} из списка слов {words} не существует слова, которое соответствует категории {category}.",
        rf"нет{punct} из списка слов, указанных в вопросе, только {category_word} входит в категорию {category}.",
        rf"нет{punct} из списка слов, которые вы предоставили, не было включено ни одного слова в категорию {category}.",
        rf"нет{punct} из списка слов, перечисленных в вашем вопросе, только слово {category_word} может быть отнесено к категории {category}.",
        rf"нет{punct} из списка слов, перечисленных в вашем вопросе, только слово {category_word} может быть отнесено к категории {category}.",
        rf"нет{punct} из списка слов, которые вы предоставили, нет слов, входящих в категорию {category}. как только слово {category_word} входит в эту категорию, но не {distractors}.",
        rf"нет{punct} слова {distractors} не являются {category}.",
        rf"нет{punct} слова {distractors} не относятся к категории {category}.",
        rf"нет{punct} слова {distractors} не относятся к категории {category}. категория {category} включает в себя только слова {category_word}.",
        rf"да{punct} слова {category_word} и {category} ассоциируются с категорией {category}.",
        rf"нет{punct} нет связей между любым словом из списка и категорией {category}.",
        rf"нет{punct} нет связей между любыми словами из списка и категорией {category}.",
        rf"нет{punct} нет связей между словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не связано' for distractor in distractors])}",
        rf"нет{punct} нет связей между любыми словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не связано' for distractor in distractors])}",
        rf"нет{punct} нет связей между любыми словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - это не {category}' for distractor in distractors])}",
        rf"нет{punct} нет связей между словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не связан с {category}' for distractor in distractors])}",
        rf"нет{punct} нет связей между любыми словами из списка и категорией {category}.",
        rf"нет{punct} нет связей между любыми словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не связано с {category}' for distractor in distractors])}",
        rf"да{punct} слова {category_word} и {category} находятся в категории {category}.",
        rf"да{punct} слова {category_word} и {category} представляют категорию {category}.",
        rf"да{punct} слова {category_word} и {category} соответствуют категории {category}.",
        rf"да{punct} слова {category_word} и {category} имеют связь с категорией {category}.",
        rf"да{punct} слова {category_word} и {category} согласованы с категорией {category}.",
        rf"да{punct} слова {category_word} и {category} имеют связь с категорией {category}.",
        rf"да{punct} слова {category_word} и {category} согласуются с категорией {category}.",
        rf"да{punct} слова {category_word} и {category} относятся к этой категории.",
        rf"да{punct} слова {category_word} и {category} находятся в одной категории.",
        rf"да{punct} слова {category_word} и {category} входят в категорию {category}.",
        rf"да{punct} слова {category_word} и {category} относятся к одной и той же категории.",
        rf"да{punct} слова {category_word} и {category} находятся в одной категории.",
        rf"да{punct} слова {category_word} и {category} согласованы.",
        rf"да{punct} слова {category_word} и {category} могут быть объединены в категорию {category}.",
        rf"да{punct} слова {category_word} входят в категорию {category}.",
        rf"да{punct} слова {category_word} включены в категорию {category}.",
        rf"да{punct} слова {category_word} относятся к категории {category}.",
        rf"да{punct} слово {category_word} входит в категорию {category}.",
        rf"да{punct} слово {category_word} можно отнести к категории {category}.",
        rf"нет{punct} {words} не являются {category}.",
        rf"нет{punct} {words} не относятся к категории {category}.",
        rf"нет{punct}\n{words} не являются частью категории {category}.",
        rf"нет{punct}\n{words} не являются {category}. они являются различными словами, которые не связаны между собой какой-либо темой или категорией.",
        rf"да{punct} категория {category} может включать слово {category_word}.",
        rf"из выданных слов, только {category_word} имеет отношение к категории {category}.",
        rf"нет{punct} {distractors} не являются {category}.",
        rf"да{punct} {category_word} является {category}.",
        rf"да{punct} {category_word} является категорией {category}.",
        rf"да{punct} {category_word} является частью категории {category}.",
        rf"да{punct} слово {category} связано с категорией {category_word}.",
        rf"нет{punct} ни один из слов из списка {words} не входит в категорию {category}.",
        rf"нет{punct} ни один из слов из списка {words} не связано с категорией {category}.",
        rf"да{punct} слово {category_word} включается в категорию {category}.",
        rf"да{punct} слово {category_word} соотносимо с категорией {category}.",
        rf"да{punct} слово {category_word} согласовано с категорией {category}.",
        rf"да{punct} слово {category_word} будет включаться в категорию {category}.",
        rf"да{punct} слова {category_word} и {category} относятся к категории {category}, а слова {distractors} не относятся к этой категории.",
        rf"нет{punct} нет согласований между словами из списка {words} и категорией {category}.",
        rf"нет{punct} нет согласований с категорией {category} для всех слов в списке:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не согласовано' for distractor in distractors])}",
        rf"нет{punct} нет согласований с категорией {category} для любого из этих слов:\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - нет согласования' for distractor in distractors])}",
        rf"слово {category_word} принадлежит категории {category}.",
        rf"слово {category_word} принадлежит к категории {category}. ответ: {category_word}.",
        rf"да{punct} {category} может быть связано с {category_word}.",
        rf"да{punct} {category} может быть связан с словом {category_word}.",
        rf"да{punct} слово {category_word} можно отнести к категории {category}.",
        rf"да{punct} слово {category_word} можно объединить в категорию {category}.",
        rf"нет{punct} нет совпадений между словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не является {category}' for distractor in distractors])}",
        rf"ответ: нет. ни один из слов из списка {words} не относится к категории {category}.",
        rf"ответ: нет. ни один из слов из списка {words} не имеет отношения к категории {category}.",
        rf"да{punct} {category_word} можно отнести к категории {category}.",
        rf"да{punct} слова {category_word} входят в категорию {category}.",
        rf"нет{punct}\nв списке перечислены следующие {category}:\n* {category_word}\n\nостальные слова {distractors} не являются {category}.",
        rf"да{punct} слово {category_word} включено в категорию {category}.",
        rf"нет{punct} нет соотношений между словами из списка {words} и категорией {category}.",
        rf"нет{punct} нет соотношений между словами из списка и категорией {category}.\n{r'\n\* ' + r'\n\* '.join([rf'"{distractor}" - не связано с {category}' for distractor in distractors])}",
        rf"да{punct} слово {category_word} находится в категории {category}.",
        rf"слово {category_word} соотносится с категорией {category}.",
        rf"слово {category_word} соотносится с категорией {category}. ответ: {category_word}.",
        rf"да{punct} {category} включает в себя слово {category_word}.",
        rf"да{punct} {category_word} относится к категории {category}.",
        rf"нет{punct} никакое из слов из списка не входит в категорию {category}.",
        rf"да{punct} слово {category_word} можно отнести к категории {category}, так как оно описывает тип {category}.",
        rf"слово {category_word} соответствует категории {category}, поэтому ответ - {category_word}.",
        rf"слово {category_word} попадает в категорию {category}.",
        rf'слово {category_word} входит в категорию {category}.\n\nответ: да.',
        rf"слово {category_word} имеет отношение к категории {category}, поэтому ответ - {category_word}.",
        rf'слово {category_word} согласовано с категорией {category}. ответ: "да".',
        rf"да{punct} {category_word} принадлежит к категории {category}.",
        rf"да{punct} {category_word} соответствует категории {category}.",
        rf"да{punct} {category_word} - это слово, которое соответствует категории {category_word}.",
        rf"да{punct} {category_word} связана с категорией {category}.",
        rf"да{punct} {category_word} попадает в категорию {category}.",
        rf"да{punct} {category_word} имеет отношение к категории {category}.",
        rf"да{punct} {category_word} имеет связь с категорией {category}.",
        rf"да{punct} связь с категорией {category} есть у слова {category_word}.",
        rf"да{punct} {category_word} связано с категорией {category}.",
        rf"да{punct} {category_word} связан с категорией {category}.",
        rf"да{punct} {category_word} может быть отнесено к категории {category}.",
        rf"да{punct} {category} является частью категории {category_word}.",
        rf"да{punct} {category_word} может быть ассоциировано с категорией {category}.",
        rf"да{punct} {category_word} входит в категорию {category}.",
        rf"да{punct} {category_word} может быть отнесена к категории {category}.",
        rf"нет{punct}\n{words} - это отдельные слова, не являющиеся частью какой-либо категории {category}."
    ]
